disabled_rules:
  - trailing_whitespace
  - force_try
  - force_cast
  - function_body_length

# Rule Config
line_length: 150
identifier_name:
  allowed_symbols: "r"
  min_length: 1
  max_length:
    warning: 40
    error: 60
type_name:
  min_length: 3
  max_length:
    warning: 80
    error: 100

# General Config
excluded:
  - Pods
  - Tuist
  - Setup.swift
  - Workspace.swift
  - Core/Tests
  - Common/Tests
  - VatPayerChecker/Tests
  - VatPayerChecker/UITests
